### ISSUE TITLE
won't install after latest update

### ISSUE THREAD

**Issue by rcrooks** [SydLambert/atom-mesa-syntax#2]
Hi @SydLambert - your beautiful syntax won't install for me anymore after the latest update. I haven't dug but suspect something wrong in the package file. It does show up under updates, but install fails. Under Install, only the .4 version shows up.

**Comment by rcrooks** [comment]
ah, not sure if you did another update or it was just some issue on my machine, but seems ok now.

**Comment by SydLambert** [comment]
Hi, sorry I couldn't respond earlier. Yeah, I was fiddling about with the versioning and I think I broke something; I'm still very new to Atom packages and still learning. I pushed an update yesterday that should have fixed it, maybe the old update was cached somewhere or something. I tested the update on Windows & mac, and was able to recreate your issue on Linux, I fixed it by uninstalling the package and restarting Atom before reinstalling. The problem might have been caused by Atom's release version tags not matching those in Github.

P.S Thanks for your kind words about my theme, it means a lot :)
